### ISSUE TITLE
widget error

### ISSUE THREAD

**Issue by skydiver** [vojtasvoboda/oc-useraccesslog-plugin#1]
I'm getting this error when trying to add widget to dashboard:

```
exception 'ErrorException' with message 'Undefined variable: all' in /SERVER/www/plugins/vojtasvoboda/useraccesslog/reportwidgets/accesslogstatistics/partials/_widget.htm:3
```

**Comment by vojtasvoboda** [comment]
Thank you for feedback. New update it now available for update. Would you mind to try it please?

**Comment by vojtasvoboda** [comment]
Let me know if it's OK and I close this issue. Thanks!

**Comment by skydiver** [comment]
The dashboard exception it's fixed.

The problem was because i've deleted some users.

Now i get a grey empty pie chart.

If i delete the logs records with **`user_id = 0`** the chart displays data again.

**Comment by vojtasvoboda** [comment]
I fix that problem by showing "Deleted users" record. It is now available as update 1.0.4.

Thank you for your valuable feedback!

I don't want to complete hide deleted users because I'm preparing new types of graphs (based on time) and accesses of deleted users should be also included as part of previous traffic. Will be available today or tomorrow.

**Comment by vojtasvoboda** [comment]
I just make an update 1.0.5. with new dashboard widgets. Would you mind to test it please? Thanks a lot :-)

**Comment by skydiver** [comment]
1) Default widget works great
2) Strange ... no translation loaded on any widget ...

![screenshot from 2016-04-15 19 46 04](https://cloud.githubusercontent.com/assets/578784/14576783/bf8965c4-0342-11e6-89e1-a2bef7090b36.png)

![screenshot from 2016-04-15 19 48 07](https://cloud.githubusercontent.com/assets/578784/14576802/00ca7a3c-0343-11e6-9e4b-acc1b1f3cc04.png)

**Comment by vojtasvoboda** [comment]
Yes the same issue at me, but when you click on widget settings and close it, the default value is magically set. I don't know why (yet).

**Comment by skydiver** [comment]
You're right

**Comment by vojtasvoboda** [comment]
Looks like a bug in OctoberCMS. I temporarily remove translations for a default value, it is available as an update.
