### ISSUE TITLE
Visit counter for non users & userss

### ISSUE THREAD

**Issue by bkrajendra** [vojtasvoboda/oc-useraccesslog-plugin#6]
Is it possible to add just visit log for non members to site. just like a visit counter. this can be a frontend component to show visitor counter along with number of members online + guest online.

**Comment by vojtasvoboda** [comment]
If you need this function, please send me a pull-request, I will check it. I'm now working on other plugins, so I'm not able to do this in a next few months :-(

But I think you can also use Google Analytics plugin (for free).
