### ISSUE TITLE
Additional reporting features

### ISSUE THREAD

**Issue by LarryBarker** [vojtasvoboda/oc-useraccesslog-plugin#7]
I'm interested in building out some additional reporting features. For instance, for the Access Log Statistics report, I would like to be able to specify a certain time frame, like some of the other reports do. I would also like to specify certain user groups. 

I tried copying over code from AccessLogChartLineAggregated.php:
'        $days = $this->property('days');
        if (!$days) {
            throw new ApplicationException('Invalid days value: ' . $days);
        }

        // all accesses for last month
        $items = AccessLog::where('created_at', '>=', Carbon::now()->subDays($days)->format('Y-m-d'))->get();'

but it is not returning any results. Note I added a days property for the report widget.

Would you be willing to work with me to implement this feature?

**Comment by vojtasvoboda** [comment]
Hi @WWRFresource, thanks for your interest. Please check your database table `user_access_log` if there is any record.

I tried to insert this code to Plugin.php boot() method, just to check it:

```
dd(AccessLog::where('created_at', '>=', Carbon::now()->subDays(30)->format('Y-m-d'))->get());
```

and it gives me correctly content of `user_access_log` table:

![snimek obrazovky 2017-08-23 v 23 02 25](https://user-images.githubusercontent.com/374917/29638314-2a4a4302-8857-11e7-8d34-66367433f2f2.png)

**Comment by LarryBarker** [comment]
Solved with this code:
`$log = AccessLog::whereHas('user', function($q)
        {
            $q->whereHas('groups', function($subquery)
                {
                    $subquery->where('name', $this->property('group'));
                });
        })->where('created_at', '>=', Carbon::now()->subDays($days)->format('Y-m-d'))->get()->groupBy('user_id');`
