### ISSUE TITLE
User Access Log Table Widget

### ISSUE THREAD

**Issue by juanmoyano** [vojtasvoboda/oc-useraccesslog-plugin#9]
Hi, I'm trying your plugin and it's looking good!
I'm wondering how difficult would it be to create a widget that shows last user logins (or configurable by a date range) in a table sorted by access date.
Has someone tried it before? If I were to contribute and code it, where should I be looking at to start?
Thank you very much for your work!
Best regards.

**Comment by vojtasvoboda** [comment]
@juanmoyano Version 1.1.0 with backend user access log listing is available at the OctoberCMS market, so feel free to update.

Filtering by access date included.

After update go to the Settings > User > Config access log and mark "Show access log listing". Then you will see listing at the Users module sidemenu.

**Comment by juanmoyano** [comment]
Thanks man, you're awesome! 
I would like to submit a PR with spanish translations and surname and email columns added to accesslog model, would that be ok?

**Comment by vojtasvoboda** [comment]
@juanmoyano Yes sure, send a PR and I will merge it :-)
